/*
 * Foxhole WarAPI
 *
 * The War API allows developers to query information about the state of the current Foxhole World Conquest.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FactionEnum {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "WARDENS")]
    Wardens,
    #[serde(rename = "COLONIALS")]
    Colonials,

}

impl std::fmt::Display for FactionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "NONE"),
            Self::Wardens => write!(f, "WARDENS"),
            Self::Colonials => write!(f, "COLONIALS"),
        }
    }
}

impl Default for FactionEnum {
    fn default() -> FactionEnum {
        Self::None
    }
}

