/*
 * Foxhole WarAPI
 *
 * The War API allows developers to query information about the state of the current Foxhole World Conquest.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WarReport {
    #[serde(rename = "totalEnlistments", skip_serializing_if = "Option::is_none")]
    pub total_enlistments: Option<i32>,
    #[serde(rename = "colonialCasualties", skip_serializing_if = "Option::is_none")]
    pub colonial_casualties: Option<i32>,
    #[serde(rename = "wardenCasualties", skip_serializing_if = "Option::is_none")]
    pub warden_casualties: Option<i32>,
    #[serde(rename = "dayOfWar", skip_serializing_if = "Option::is_none")]
    pub day_of_war: Option<i32>,
}

impl WarReport {
    pub fn new() -> WarReport {
        WarReport {
            total_enlistments: None,
            colonial_casualties: None,
            warden_casualties: None,
            day_of_war: None,
        }
    }
}

